"""Change lacation -> location

Revision ID: 7d10ca987a90
Revises: a2a19419c3af
Create Date: 2024-09-10 18:28:04.662372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d10ca987a90'
down_revision: Union[str, None] = 'a2a19419c3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('location', sa.String(), nullable=False))
    op.drop_column('hotels', 'lacation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('lacation', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('hotels', 'location')
    # ### end Alembic commands ###
